---
author: ICPics
cover: img/page2.png
date: "2021-12-09"
description: "Join our [Discord](https://discord.gg/gauQWrV2b4), [Twitter](https://twitter.com/ethnICPic), and [Instagram](https://www.instagram.com/ethnicpictures/)"
title: The story of the "Ultra Rare" rarity artwork
---

Unlike most other NFT collections in the cryptospace, we believed that the artwork generation must be community driven with user input, whenever applicable. With this in mind, we started our [Discord](https://discord.gg/gauQWrV2b4), [Twitter](https://twitter.com/ethnICPic), and [Instagram](https://www.instagram.com/ethnicpictures/) accounts even when our project was still in the drawing board. 

As a means of recognizing our avid supporters and participants, we wanted to generate our most rarest artworks using the themes provided by users. With this in mind, we accepted theme requests from [Discord](https://discord.gg/gauQWrV2b4) users.

The three artworks displayed above are examples of user-driven themes.

---

- PS: If you have an idea the reflect our project scope of "ethnic people communities" or "exotic places," let us know in the 🙋︱requests-and-ideas channel in our [Discord](https://discord.gg/gauQWrV2b4) server.

---

Join our [Discord](https://discord.gg/gauQWrV2b4), [Twitter](https://twitter.com/ethnICPic), and [Instagram](https://www.instagram.com/ethnicpictures/) 

We have spoken.